"""Unit tests for QueryService. No database: the service is given in-memory
fake repositories, so these exercise business rules in isolation: the parent
conversation must exist and be open, the auto-generated output uses the
conversation's chosen LLM, and an agent output (is_input=False) is stored as-is
without generating a reply."""

import pytest

from app.models.query import QueryCreate
from app.services.conversation_service import (
    ConversationEndedError,
    ConversationNotFoundError,
    ConversationService,
)
from app.services.llm_service import LLMType
from app.services.query_service import QueryNotFoundError, QueryService


def _service(fake_query_repo, fake_conversation_repo):
    return QueryService(fake_query_repo, fake_conversation_repo)


def test_input_stores_turn_and_generates_output_from_conversation_llm(
    fake_query_repo, fake_conversation_repo
):
    # conversation uses the default LLM (A)
    conv = ConversationService(fake_conversation_repo).start_conversation()
    service = _service(fake_query_repo, fake_conversation_repo)

    created = service.create_query(
        QueryCreate(query_text="hello", conversation_id=conv["id"])
    )

    assert len(created) == 2
    inp, out = created
    # input turn: exactly what the user sent
    assert inp["query_text"] == "hello"
    assert inp["is_input"] is True
    assert inp["conversation_id"] == conv["id"]
    # output turn: generated by the conversation's LLM (A)
    assert out["query_text"] == "hi, we are checking your query"
    assert out["is_input"] is False
    assert out["conversation_id"] == conv["id"]


def test_output_uses_conversation_llm_b(fake_query_repo, fake_conversation_repo):
    conv = ConversationService(fake_conversation_repo).start_conversation(
        LLMType.B
    )
    service = _service(fake_query_repo, fake_conversation_repo)

    created = service.create_query(
        QueryCreate(query_text="hello", conversation_id=conv["id"])
    )

    assert created[1]["query_text"] == "hi, please provide your fullname"


def test_agent_output_is_stored_without_generating_a_reply(
    fake_query_repo, fake_conversation_repo
):
    conv = ConversationService(fake_conversation_repo).start_conversation()
    service = _service(fake_query_repo, fake_conversation_repo)

    created = service.create_query(
        QueryCreate(
            query_text="agent says hi",
            conversation_id=conv["id"],
            is_input=False,
        )
    )

    # only the submitted output turn, no auto-generated reply
    assert len(created) == 1
    assert created[0]["is_input"] is False
    assert created[0]["query_text"] == "agent says hi"
    assert len(fake_query_repo.get_all()) == 1


def test_create_query_rejects_unknown_conversation(
    fake_query_repo, fake_conversation_repo
):
    service = _service(fake_query_repo, fake_conversation_repo)

    with pytest.raises(ConversationNotFoundError):
        service.create_query(QueryCreate(query_text="hi", conversation_id=999))


def test_create_query_rejected_when_conversation_ended(
    fake_query_repo, fake_conversation_repo
):
    conv_service = ConversationService(fake_conversation_repo)
    conv = conv_service.start_conversation()
    conv_service.end_conversation(conv["id"], quality_metric=True)
    service = _service(fake_query_repo, fake_conversation_repo)

    with pytest.raises(ConversationEndedError):
        service.create_query(
            QueryCreate(query_text="late", conversation_id=conv["id"])
        )


def test_ended_conversation_stores_no_queries(
    fake_query_repo, fake_conversation_repo
):
    # The ended check happens before any write, so nothing is persisted.
    conv_service = ConversationService(fake_conversation_repo)
    conv = conv_service.start_conversation()
    conv_service.end_conversation(conv["id"], quality_metric=True)
    service = _service(fake_query_repo, fake_conversation_repo)

    with pytest.raises(ConversationEndedError):
        service.create_query(
            QueryCreate(query_text="late", conversation_id=conv["id"])
        )

    assert fake_query_repo.get_all() == []


def test_get_query_returns_existing(fake_query_repo, fake_conversation_repo):
    conv = ConversationService(fake_conversation_repo).start_conversation()
    service = _service(fake_query_repo, fake_conversation_repo)
    created = service.create_query(
        QueryCreate(query_text="hi", conversation_id=conv["id"])
    )

    assert service.get_query(created[0]["id"]) == created[0]


def test_get_query_raises_when_missing(fake_query_repo, fake_conversation_repo):
    service = _service(fake_query_repo, fake_conversation_repo)

    with pytest.raises(QueryNotFoundError):
        service.get_query(999)


def test_list_for_conversation_returns_only_its_queries(
    fake_query_repo, fake_conversation_repo
):
    conv_service = ConversationService(fake_conversation_repo)
    conv_a = conv_service.start_conversation()
    conv_b = conv_service.start_conversation()
    service = _service(fake_query_repo, fake_conversation_repo)
    service.create_query(QueryCreate(query_text="a", conversation_id=conv_a["id"]))
    service.create_query(QueryCreate(query_text="b", conversation_id=conv_b["id"]))

    rows = service.list_for_conversation(conv_a["id"])

    # one input submission -> two turns (input + generated output), all conv_a
    assert len(rows) == 2
    assert all(r["conversation_id"] == conv_a["id"] for r in rows)
    assert rows[0]["query_text"] == "a"


def test_list_for_conversation_raises_when_conversation_missing(
    fake_query_repo, fake_conversation_repo
):
    service = _service(fake_query_repo, fake_conversation_repo)

    with pytest.raises(ConversationNotFoundError):
        service.list_for_conversation(999)
